name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os:
        - ubuntu-22.04
        - ubuntu-20.04
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: autogen
      run: ./autogen.sh

    - name: configure
      run: ./configure
      
    - name: Install dependencies
      run: make
      
    - name: Run check
      run: make check
      
#    - name: Run distcheck
#      run: make distcheck

#  build-on-mac:
  
#    runs-on: macos-latest
#    steps:
#    - name: Check out repository code
#      uses: actions/checkout@v3

#    - name: Install automake
#      run: |
#        brew update
#        brew install automake gnu-sed openssl

#    - name: autogen
#      run: ./autogen.sh

#    - name: configure
#      run: ./configure
      
#    - name: Install dependencies
#      run: make
      
#    - name: Run check
#      run: make check
      
#    - name: Run distcheck
#      run: make distcheck
